server:
  port: 9000

spring:
  application:
    name: config-server
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/81673211/spring-cloud-config-study
          search-paths: /micro-stage
          username:
          password:
      label: master


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/