eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8080

spring:
  application:
    name: gateway-zuul

zuul:
  routes:
    api-a:
      path: /user/**
      serviceId: frontend
    api-b:
      path: /news/**
      serviceId: non-exist