#server:
#  port: 9101
#eureka:
#  instance:
#    hostname: registry-server1
#  client:
#    service-url:
#      defaultZone: http://peer2:8861/eureka/,http://peer3:8961/eureka/
#    fetch-registry: false
#    register-with-eureka: false
#spring:
#  application:
#    name: registry-server
#  profiles:
#    active: dev

#---
#server:
#  port: 9102
#eureka:
#  client:
#    fetch-registry: false
#    register-with-eureka: false
#    service-url:
#      defaultZone: http://peer1:8761/eureka/,http://peer3:8961/eureka/
#  instance:
#    hostname: registry-server2
#spring:
#  profiles:
#    active: dev
#  application:
#    name: registry-server
#
#---
#server:
#  port: 9103
#eureka:
#  client:
#    fetch-registry: false
#    register-with-eureka: false
#    service-url:
#      defaultZone: http://peer1:8761/eureka/,http://peer2:8861/eureka/
#  instance:
#    hostname: registry-server3
#spring:
#  profiles:
#    active: dev
#  application:
#    name: registry-server


# single node
server:
  port: 9100
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: registry-server1
spring:
  profiles:
    active: dev
  application:
    name: registry-server