spring:
  application:
    name: frontend

server:
  port: 8763

eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"